require 'config.options'
-- require "config.lsp.handlers".setup()
-- require 'config.mappings'

--require 'manutepowa.lualine'
--require 'manutepowa.cmp'
--require 'manutepowa.lsp'
--require 'manutepowa.telescope'
--require 'manutepowa.projects'
--require 'manutepowa.treesitter'
--require 'manutepowa.autopairs'
--require 'manutepowa.comment'
--require 'manutepowa.gitsigns'
--require 'manutepowa.toggleterm'
--require 'manutepowa.nvim-tree'
--require 'manutepowa.bufferline'
--require 'manutepowa.indentline'
--require 'manutepowa.dap_config'
--require 'manutepowa.translate'
--require 'manutepowa.packer-info'
--require 'manutepowa.diff_git'
--require 'manutepowa.restclient'
--require 'manutepowa.lab'
--require 'manutepowa.neoai'

-- require 'manutepowa.dadbod'

-- Simple options
--     require 'colorizer'.setup({
--       filetypes = {
--         "typescript",
--         "typescriptreact",
--         "javascript",
--         "javascriptreact",
--         "css",
--         "html",
--         "astro",
--         "lua",
--       },
--       user_default_options = {
--         rgb_fn = true,
--         tailwind = "both",
--       },
--       buftypes = {
--         -- '*', -- seems like this doesn't work with the float window, but works with the other `buftype`s.
--         -- Not sure if the window has a `buftype` at all
--       },
--     })
